"""
Daily executive summary generated by Google Gemini API.

Primary data source: aggregation tables (agregacion_diaria, etc.).
Supplementary: highlighted news (max 3) from noticias for illustrative URLs.

Generates a concise Spanish summary tailored for the
Secretaría de Economía de Coahuila.
"""

import json
import logging
from datetime import date, timedelta
from pathlib import Path
from typing import Dict, List, Optional

from config.settings import GEMINI_API_KEY, GEMINI_MODEL
from analisis.utils import get_db_connection, clasificar_tipo

logger = logging.getLogger(__name__)

OUTPUT_DIR = Path(__file__).resolve().parents[1] / "output"


# =============================================================================
# DATA EXTRACTION (from aggregation tables only)
# =============================================================================

def get_metricas_globales(fecha: date) -> Optional[Dict]:
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT
                total_noticias,
                total_relevantes,
                total_riesgo,
                total_oportunidad,
                total_mixto,
                medios_activos
            FROM agregacion_diaria
            WHERE fecha = ?
        """, (fecha.isoformat(),))
        row = cursor.fetchone()
        if not row:
            return None
        return {
            "total_noticias": row[0] or 0,
            "total_relevantes": row[1] or 0,
            "total_riesgo": row[2] or 0,
            "total_oportunidad": row[3] or 0,
            "total_mixto": row[4] or 0,
            "medios_activos": row[5] or 0,
        }


def get_cambio_vs_ayer(fecha: date) -> Dict:
    ayer = fecha - timedelta(days=1)
    hoy = get_metricas_globales(fecha)
    anterior = get_metricas_globales(ayer)
    if not hoy or not anterior:
        return {}

    def delta(actual, previo):
        return round((actual - previo) / previo * 100, 1) if previo else None

    return {
        "noticias": delta(hoy["total_noticias"], anterior["total_noticias"]),
        "riesgo": delta(hoy["total_riesgo"], anterior["total_riesgo"]),
        "oportunidad": delta(hoy["total_oportunidad"], anterior["total_oportunidad"]),
    }


def get_top_temas(fecha: date, limit: int = 3) -> List[Dict]:
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT t.nombre, atd.total_noticias, atd.total_riesgo, atd.total_oportunidad
            FROM agregacion_tema_diaria atd
            JOIN temas t ON atd.tema_id = t.id
            WHERE atd.fecha = ?
            ORDER BY atd.total_noticias DESC
            LIMIT ?
        """, (fecha.isoformat(), limit))
        return [
            {"tema": r[0], "noticias": r[1] or 0, "riesgo": r[2] or 0, "oportunidad": r[3] or 0}
            for r in cursor.fetchall()
        ]


def get_top_regiones(fecha: date, limit: int = 3) -> List[Dict]:
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT
                CASE
                    WHEN ard.region_id = -1 THEN ard.nivel_geografico
                    ELSE COALESCE(r.nombre, ard.nivel_geografico)
                END as region,
                ard.nivel_geografico,
                ard.total_noticias,
                ard.total_riesgo
            FROM agregacion_region_diaria ard
            LEFT JOIN regiones r ON ard.region_id = r.id AND ard.region_id != -1
            WHERE ard.fecha = ?
            ORDER BY ard.total_noticias DESC
            LIMIT ?
        """, (fecha.isoformat(), limit))
        return [
            {"region": r[0], "nivel": r[1], "noticias": r[2] or 0, "riesgo": r[3] or 0}
            for r in cursor.fetchall()
        ]


def get_top_entidades(fecha: date, limit: int = 5) -> List[Dict]:
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT e.nombre_canonico, e.tipo, aed.menciones, aed.noticias_riesgo
            FROM agregacion_entidad_diaria aed
            JOIN entidades e ON aed.entidad_id = e.id
            WHERE aed.fecha = ?
            ORDER BY aed.menciones DESC
            LIMIT ?
        """, (fecha.isoformat(), limit))
        return [
            {"entidad": r[0], "tipo": r[1], "menciones": r[2] or 0, "contexto_riesgo": r[3] or 0}
            for r in cursor.fetchall()
        ]


def get_highlighted_news(fecha: date, limit: int = 3) -> List[Dict]:
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT titulo, medio, temas, riesgo, oportunidad, nivel_geografico, url
            FROM noticias
            WHERE relevante = 1 AND fecha = ?
            ORDER BY score DESC, fecha DESC
            LIMIT ?
        """, (fecha.isoformat(), limit))
        return [
            {
                "titulo": r[0],
                "medio": r[1],
                "tema": r[2] or "Sin tema",
                "tipo": clasificar_tipo(r[3], r[4]),
                "region": r[5] or "Nacional",
                "url": r[6] or "",
            }
            for r in cursor.fetchall()
        ]


# =============================================================================
# PAYLOAD CONSTRUCTION
# =============================================================================

def construir_payload(fecha: date) -> Optional[Dict]:
    metricas = get_metricas_globales(fecha)
    if not metricas:
        logger.warning(f"No aggregation data found for {fecha.isoformat()}")
        return None
    return {
        "fecha": fecha.isoformat(),
        "metricas_globales": metricas,
        "cambio_vs_ayer": get_cambio_vs_ayer(fecha),
        "top_temas": get_top_temas(fecha, limit=3),
        "top_regiones": get_top_regiones(fecha, limit=3),
        "top_entidades": get_top_entidades(fecha, limit=5),
        "noticias_destacadas": get_highlighted_news(fecha, limit=3),
    }


# =============================================================================
# GEMINI SUMMARY
# =============================================================================

PROMPT_TEMPLATE = """Eres el analista de inteligencia de medios de la Secretaría de Economía de Coahuila.
El secretario requiere un resumen ejecutivo diario. Usa EXCLUSIVAMENTE los datos proporcionados.

CONTEXTO INSTITUCIONAL: Coahuila es el 3er estado exportador de México. Sectores clave: automotriz \
(nearshoring), siderúrgico (AHMSA), minero-carbonífero y agroindustrial. Frontera con Texas \
(Piedras Negras, Ciudad Acuña). Relevante: inversión extranjera, aranceles, empleo, política industrial.

DATOS DEL DÍA:
{json_payload}

ESTRUCTURA DEL RESUMEN:
1. Párrafo 1: panorama general del día — volumen de noticias y cambio vs día anterior.
2. Párrafo 2: temas principales con su balance riesgo/oportunidad e implicaciones económicas para Coahuila.
3. Párrafo 3: entidades y regiones con mayor actividad noticiosa.
4. Párrafo 4: referencia a 2-3 noticias destacadas con título, medio y enlace.
   Formato de enlace: "Ver nota completa: [URL]"

REGLAS:
- No inventes información que no esté en los datos.
- Si hay noticias de comercio exterior, aranceles o inversión, dales prioridad en el párrafo 2.
- Tono neutral e institucional.
- Máximo 280 palabras.
- Sin markdown ni listas, solo prosa continua.

RESUMEN:
"""


def generar_resumen_llm(payload: Dict) -> Optional[str]:
    """Generate executive summary using Gemini API."""
    if not GEMINI_API_KEY:
        logger.error("GEMINI_API_KEY not set. Cannot generate summary.")
        return None

    try:
        import google.generativeai as genai
        genai.configure(api_key=GEMINI_API_KEY)
        model = genai.GenerativeModel(GEMINI_MODEL)
    except Exception as e:
        logger.error(f"Could not initialize Gemini: {e}")
        return None

    prompt = PROMPT_TEMPLATE.format(
        json_payload=json.dumps(payload, indent=2, ensure_ascii=False)
    )

    try:
        response = model.generate_content(
            prompt,
            generation_config={"temperature": 0.2, "max_output_tokens": 700},
        )
        return response.text.strip()
    except Exception as e:
        logger.error(f"Error calling Gemini: {e}")
        return None


# =============================================================================
# OUTPUT
# =============================================================================

def guardar_resumen(fecha: date, resumen: str) -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_DIR / f"resumen_llm_{fecha.isoformat()}.txt"
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"RESUMEN EJECUTIVO — {fecha.isoformat()}\n")
        f.write("Secretaría de Economía de Coahuila\n")
        f.write("=" * 50 + "\n\n")
        f.write(resumen)
        f.write("\n")
    return filepath


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def generar_resumen_diario_llm(fecha: Optional[date] = None) -> Optional[Path]:
    """Generate daily executive summary using Gemini API."""
    if fecha is None:
        fecha = date.today()

    logger.info(f"Generating Gemini summary for {fecha.isoformat()}...")

    payload = construir_payload(fecha)
    if not payload:
        logger.error("Failed to build payload — no data available")
        return None

    resumen = generar_resumen_llm(payload)
    if not resumen:
        logger.error("Failed to generate summary from Gemini")
        return None

    filepath = guardar_resumen(fecha, resumen)
    logger.info(f"Summary saved to: {filepath}")
    return filepath


# =============================================================================
# CLI
# =============================================================================

if __name__ == "__main__":
    import sys

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    if len(sys.argv) > 1:
        try:
            target_date = date.fromisoformat(sys.argv[1])
        except ValueError:
            print(f"Formato de fecha inválido: {sys.argv[1]}. Usa YYYY-MM-DD")
            sys.exit(1)
    else:
        target_date = date.today()

    result = generar_resumen_diario_llm(target_date)
    if result:
        print(f"\nResumen generado: {result}")
        print("\nContenido:")
        print("-" * 50)
        print(result.read_text(encoding="utf-8"))
    else:
        print("No se pudo generar el resumen. Verifica que GEMINI_API_KEY esté configurada.")
        sys.exit(1)
